name: VoidFish
version: '1.0-SNAPSHOT'
main: ren.lawliet.voidFish.VoidFish
api-version: '1.20'
softdepend: [PlaceholderAPI]
depend: [Multiverse-Core]
commands:
  vWorld:
    usage: /vWorld
    description: World Command
    aliases: [ vw ]
  vGame:
    usage: /vGame
    description: Game Command
    aliases: [ vg ]