name: VoidFish
version: '1.0-SNAPSHOT'
main: ren.lawliet.voidFish.VoidFish
api-version: '1.20'
softdepend: [PlaceholderAPI]
depend: [Multiverse-Core]
commands:
  vfWorld:
    usage: /vfWorld
    description: World Command
    aliases: [ vfw ]
  vfGame:
    usage: /vfGame
    description: Game Command
    aliases: [ vfg ]